Repository Team-TrackUs/Trackus-iOS, pull requests merged in 2024-06, with the labels that each got.

#39 [#37] 공유하기 기능추가
  .DS_Store
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/Subtract.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/Subtract.imageset/Subtract.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/photo_cell.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/photo_cell.imageset/photo_cell.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/photo_cell2.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/photo_cell2.imageset/photo_cell2.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test1.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test1.imageset/test1.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test2.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test2.imageset/test2.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test3.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test3.imageset/test3.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test4.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test4.imageset/test4.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test5.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test5.imageset/test5.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test6.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test6.imageset/test6.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test7.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test7.imageset/test7.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test8.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/test8.imageset/test8.png
  TrackUs-iOS/TrackUs-iOS/Common/Extension/UIImage+.swift
  TrackUs-iOS/TrackUs-iOS/Common/Service/RecordService.swift
  TrackUs-iOS/TrackUs-iOS/Common/Shared/UserManager.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/RecordSharing/Controllers/DataCollectionVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/RecordSharing/Controllers/PhotoEditVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/RecordSharing/Controllers/SelectePhotoVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/RecordSharing/Controllers/StickerCollectionVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/RecordSharing/Views/DataCollectionCell.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/RecordSharing/Views/StickerCollectionCell.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/Controllers/RunTrackingVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/Controllers/RunningResultVC.swift
Labels: 기능추가, UI

#42 [#25] 다른 사용자 차단 및 신고 기능 구현
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/dots_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/dots_icon.imageset/dots_icon.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/profileChat_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/profileChat_icon.imageset/profileChat_icon.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/profileblock_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/profileblock_icon.imageset/profileblock_icon.png
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/MyProfileEditVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/MyProfileVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/OtherProfileVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/ReportUserVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/SettingVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/UserListVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/WithdrawalVC.swift
Labels: 기능추가, UI

#48 [#47] 사진공유 템플릿추가 및 전체적인 오류수정
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/photo_cell.imageset/photo_cell.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/photo_cell2.imageset/photo_cell2.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/photo_cell3.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/photo_cell3.imageset/photo_cell3.png
  TrackUs-iOS/TrackUs-iOS/Common/Core/AppDelegate.swift
  TrackUs-iOS/TrackUs-iOS/Common/Extension/Array+.swift
  TrackUs-iOS/TrackUs-iOS/Common/Shared/WidgetManager.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/RecordSharing/Controllers/DataCollectionVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/RecordSharing/Controllers/PhotoEditVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/RecordSharing/Controllers/SelectePhotoVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/Controllers/MapResultVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/Controllers/RunInfoDetailVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/Controllers/RunTrackingVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/Controllers/RunningResultVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/WidgetAttribute.swift
  TrackUs-iOS/WidgetTest/Assets.xcassets/Gray1.colorset/Contents.json
  TrackUs-iOS/WidgetTest/Assets.xcassets/trackus_icon.imageset/Contents.json
  TrackUs-iOS/WidgetTest/Assets.xcassets/trackus_icon.imageset/trackus_icon.png
  TrackUs-iOS/WidgetTest/WidgetTestLiveActivity.swift
Labels: 버그, 기능추가, UI

#51 [#25, #49] 마이페이지 수정
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/profileMinus_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/profileMinus_icon.imageset/profileMinus_icon.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/profilePlus_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/profilePlus_icon.imageset/profilePlus_icon.png
  TrackUs-iOS/TrackUs-iOS/Common/Service/UserManager.swift
  TrackUs-iOS/TrackUs-iOS/Model/report_user.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Auth/View/NicknameInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/MyProfileEditVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/MyProfileVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/OtherProfileVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/ProfileRecordsCell.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/ReportUserVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/SettingVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/UserListVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/WithdrawalVC.swift
Labels: 기능추가, UI

#56 [#38]모집글 탈퇴회원의 셀이 없어지는 오류 수정
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs-iOS/TrackUs-iOS.xcodeproj/xcshareddata/xcschemes/TrackUs-iOS.xcscheme
  TrackUs-iOS/TrackUs-iOS/Common/Service/PostService.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseDetailVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/View/MatePeopleListCell.swift
Labels: 버그, 기능추가

#58 [Fix] 차단하기 기능 수정
  TrackUs-iOS/TrackUs-iOS/Common/Service/PostService.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/View/MatePeopleListCell.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Profile/Controllers/ReportUserVC.swift
Labels: 버그

#61 [#38] 모집글 등록뷰에 warningText 추가
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseRegisterVC.swift
Labels: UI
