Repository Team-TrackUs/Trackus-iOS, pull requests merged in 2024-05, with the labels that each got.

#6 Update .gitignore
  .gitignore
Labels: 문서수정

#12 [#11] 라이브트래킹 상태변화에 따른 UI/UX 개선
  .DS_Store
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/altitude_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/altitude_icon.imageset/altitude_icon.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/footprint_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/footprint_icon.imageset/footprint_icon.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/pulse_icon.imageset/pulse_icon.png
  TrackUs-iOS/TrackUs-iOS/Common/Shared/LocationService.swift
  TrackUs-iOS/TrackUs-iOS/Model/Record.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/Controllers/RunActivityVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/Services/RunTrackingManager.swift
Labels: 기능추가, UI

#13 Feature/recruitment
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Colors/SubBlue.colorset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/locationPin_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/locationPin_icon.imageset/Vector (2).png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/pencil_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/pencil_icon.imageset/Group 618.png
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/people_icon.imageset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Image/people_icon.imageset/ic_round-people.png
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseDetailVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseDrawingMapVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseMapVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseRegisterVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/MateDetailVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/MateDetailVC2.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/RunningMateVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/SearchVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/View/MatePeopleListCell.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/View/MateViewCell.swift
Labels: UI

#14 [#3] kakao로그인 추가
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Colors/White.colorset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Common/Component/MainButton.swift
  TrackUs-iOS/TrackUs-iOS/Common/Core/AppDelegate.swift
  TrackUs-iOS/TrackUs-iOS/Common/Core/SceneDelegate.swift
  TrackUs-iOS/TrackUs-iOS/Common/Extension/UIImage+.swift
  TrackUs-iOS/TrackUs-iOS/Common/Service/AuthService.swift
  TrackUs-iOS/TrackUs-iOS/Config.xcconfig
  TrackUs-iOS/TrackUs-iOS/Info.plist
  TrackUs-iOS/TrackUs-iOS/Model/User.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/Controllers/LoginVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/Controllers/SignUpVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/AgreementInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/NicknameInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/ProfilePictureInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/ProfilePublicView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/SplashView.swift
Labels: 기능추가, UI

#15 git에서 key파일 삭제
  .DS_Store
  .gitignore
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs-iOS/TrackUs-iOS/Config.xcconfig
  TrackUs-iOS/TrackUs-iOS/GoogleService-Info.plist
  TrackUs-iOS/TrackUs-iOS/Info.plist
  TrackUs-iOS/TrackUs-iOS/Model/Running.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/Controllers/SignUpVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/NicknameInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Running/Services/RunTrackingManager.swift
Labels: 문서수정

#18 [#3] 회원가입 Firebase 데이터 등록, 약관 상세 페이지 보기 버튼 추가
  TrackUs-iOS/TrackUs-iOS/Common/Extension/UIImage+.swift
  TrackUs-iOS/TrackUs-iOS/Common/Service/AuthService.swift
  TrackUs-iOS/TrackUs-iOS/Model/User.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/Controllers/SignUpVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/AgreementInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/NicknameInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/ProfilePictureInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/ProfilePublicView.swift
Labels: 기능추가, UI

#23 [#3, #16]ImageCacheManager 구현 및 본인 정보 확인 추가
  .DS_Store
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS/Common/Component/MainButton.swift
  TrackUs-iOS/TrackUs-iOS/Common/Core/SceneDelegate.swift
  TrackUs-iOS/TrackUs-iOS/Common/Service/AuthService.swift
  TrackUs-iOS/TrackUs-iOS/Common/Service/ImageCacheManager.swift
  TrackUs-iOS/TrackUs-iOS/Common/Shared/UserManager.swift
  TrackUs-iOS/TrackUs-iOS/GoogleService-Info.plist
  TrackUs-iOS/TrackUs-iOS/Model/User.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/Controllers/SignUpVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/NicknameInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Auth/View/ProfilePictureInputView.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Chat/Controllers/MyChatListVC.swift
Labels: 기능추가

#22 [#17] 모집글 등록, 참여, 나가기, 검색 기능추가
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Colors/Interval.colorset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Colors/Jogging.colorset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Colors/Running.colorset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Assets.xcassets/Colors/Walking.colorset/Contents.json
  TrackUs-iOS/TrackUs-iOS/Common/Service/PostService.swift
  TrackUs-iOS/TrackUs-iOS/Model/Post.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseDetailVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseDrawingMapVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseMapVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseRegisterVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/RunningMateVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/SearchVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/View/MateViewCell.swift
Labels: 기능추가

#27 [#17] 테이블뷰 Custom Refresh 추가, 무한 스크롤 기능 구현, 검색 기능 수정, 모집글 버튼 비활성화 기능 추가
  .DS_Store
  TrackUs-iOS/TrackUs-iOS.xcodeproj/project.pbxproj
  TrackUs-iOS/TrackUs-iOS/Common/Service/PostService.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseDetailVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseDrawingMapVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/CourseRegisterVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/RunningMateVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/Controllers/SearchVC.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/View/MatePeopleListCell.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/View/MateViewCell.swift
  TrackUs-iOS/TrackUs-iOS/Presentation/Mate/View/RefreshView.swift
Labels: 기능추가, UI
